const fs = require('fs');
const path = require('path');

const envPath = path.join(__dirname, '.env');
if (fs.existsSync(envPath)) {
    const envContent = fs.readFileSync(envPath, 'utf8');
    envContent.split('\n').forEach(line => {
        const [key, value] = line.split('=');
        if (key && value) {
            process.env[key.trim()] = value.trim();
        }
    });
}

const geminiKey = process.env.EXPO_PUBLIC_GEMINI_API_KEY || '';
const elevenLabsKey = process.env.EXPO_PUBLIC_ELEVENLABS_API_KEY || '';

const secretsContent = `// Auto-generated by generate-secrets.js
import Foundation

struct Secrets {
    static let geminiApiKey = "${geminiKey}"
    static let elevenLabsApiKey = "${elevenLabsKey}"
}
`;

const widgetPath = path.join(__dirname, 'widget');
if (fs.existsSync(widgetPath)) {
    fs.writeFileSync(path.join(widgetPath, 'Secrets.swift'), secretsContent);
    console.log('Secrets.swift generated successfully.');
} else {
    console.error('Widget directory not found.');
}
